test-test:
  cdh: cdh6
  username: qing
  password: 123456
  jdbcUrl: jdbc:oracle:thin:@localhost:1521/XE
  sql:
03-yx:
  cdh: cdh6
  username: SHUJUZHILIANG
  password: shujuzhiliang#2015
  jdbcUrl: jdbc:oracle:thin:@10.150.26.136:1530/YXGLDB
  tableName: fed_design_meas_device_unique
03-cw:
  cdh: cdh6
  username: FMISQUERY
  password: FMISQUERY.1234
  jdbcUrl: jdbc:oracle:thin:@10.150.27.142:1522/OLTP
03-kkx:
  cdh: cdh6
  username: GGADM
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.150.26.162:1540/SHAREDB
03-gis:
  cdh: cdh6
  username: CSGII_GDGIS
  password: hello_123
  jdbcUrl: jdbc:oracle:thin:@10.150.26.11:1578/GDGIS
03-rz:
  cdh: cdh6
  username: DMHS
  password: dmhs123456
  jdbcUrl: jdbc:oracle:thin:@10.150.27.19:5237

06-yx:
  cdh: cdh6
  username: ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.164.224.20:7027/yxtydb

06-zc:
  cdh: cdh6
  username: ggadm
  password: ggadm#0627
  jdbcUrl: jdbc:oracle:thin:@10.115.145.248:7027/SJZXZCTY

06-gis:
  cdh: cdh6
  username: ggadm
  password: ggadm#0627
  jdbcUrl: jdbc:oracle:thin:@10.115.145.250:7027/sjzxgsty

06-cw:
  cdh: cdh6
  username: ggadm
  password: Gzdw1234#
  jdbcUrl: jdbc:oracle:thin:@10.115.145.251:7027/sjzxzhty


09-yx:
  cdh: cdh6
  username: ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.150.41.182:1522/PMSSC

09-zc:
  cdh: cdh6
  username: ogg
  password: ogg1*oracle
  jdbcUrl: jdbc:oracle:thin:@10.150.41.175:1522/LCAM_DG

09-gis:
  cdh: cdh6
  username: ogg
  password: ogg1*oracle
  jdbcUrl: jdbc:oracle:thin:@10.150.41.51:1522/SGISDB_DG

09-cw:
  cdh: cdh6
  username: ogg
  password: ogg1*oracle
  jdbcUrl: jdbc:oracle:thin:@10.150.41.228:1522/szplus_dg

09-kkx:
  cdh: cdh6
  username: ggs
  password: 1*oracle
  jdbcUrl: jdbc:oracle:thin:@10.150.32.116:1522/ypsjdb

05-yx:
  cdh: cdh6
  username: YX_NWSJZXCX_YN
  password: wc1zDoi+
  jdbcUrl: jdbc:oracle:thin:@10.111.241.228:1522/yxgldb

05-zc:
  cdh: cdh6
  username: oggadm
  password: yN4ZdK=iq
  jdbcUrl: jdbc:oracle:thin:@10.111.6.50:1523/ynzcdg

05-gis:
  cdh: cdh6
  username: oggadm
  password: yN4ZdK=iq
  jdbcUrl: jdbc:oracle:thin:@10.111.6.105:1523/nwgisdb

05-cw:
  cdh: cdh6
  username: ggadm
  password: Oggadm%123
  jdbcUrl: jdbc:oracle:thin:@10.111.242.67:1523/nwcwzjk

05-kkx:
  cdh: cdh6
  username: oggadm
  password: yN4ZdK=iq
  jdbcUrl: jdbc:oracle:thin:@10.111.12.73:1523/sharedb

05-rz:
  cdh: cdh6
  username: ogg
  password: ogg#2019
  jdbcUrl: jdbc:oracle:thin:@10.111.242.51:1523/ywrzdb

04-yx:
  cdh: cdh6
  username: GXYXRO
  password: OraCsg_123
  jdbcUrl: jdbc:oracle:thin:@10.100.102.10:21521/yxgldb

04-zc:
  cdh: cdh6
  username: GXZCRO
  password: OraCsg_123
  jdbcUrl: jdbc:oracle:thin:@10.100.102.11:21521/scxtdb

04-gis:
  cdh: cdh6
  username: GXGISRO
  password: OraCsg_123
  jdbcUrl: jdbc:oracle:thin:@10.100.102.14:21521/gisdb

04-cw:
  cdh: cdh6
  username: GXCWRO
  password: OraCsg_123
  jdbcUrl: jdbc:oracle:thin:@10.100.102.12:21521/plusdb

04-kkx:
  cdh: cdh6
  username: GXYPRO
  password: OraCsg_123
  jdbcUrl: jdbc:oracle:thin:@10.100.102.15:21521/yporcl

04-rz:
  cdh: cdh6
  username: GXRZRO
  password: OraCsg_123
  jdbcUrl: jdbc:oracle:thin:@10.100.102.13:21521/hrscdb

08-yx:
  cdh: cdh6
  username: hy_liujundi2_ro
  password: SJCQ_y.t0625
  jdbcUrl: jdbc:oracle:thin:@10.174.217.20:1621/gymmgl

08-zc:
  cdh: cdh6
  username: KTP_YINWEIQI_RO
  password: Gzj#20191212
  jdbcUrl: jdbc:oracle:thin:@10.174.16.153:1621/EAM

08-gis:
  cdh: cdh6
  username: G_PSR_NW
  password: G_PSR_NW#123
  jdbcUrl: jdbc:oracle:thin:@10.150.154.199:1621/BGISDB

08-cw:
  cdh: cdh6
  username: yg_zhangwenliang_ro
  password: yg_zhangwenliang_ro#ora_01555
  jdbcUrl: jdbc:oracle:thin:@10.150.145.145:1621/CWPLUS

08-kkx:
  cdh: cdh6
  username: CSG_NWGP_YP
  password: NW_nwgp0315
  jdbcUrl: jdbc:oracle:thin:@10.150.145.61:1621/YPJCDB

08-rz:
  cdh: cdh6
  username: CSG_SJZL_RZ
  password: gzj_rz_1119
  jdbcUrl: jdbc:oracle:thin:@10.150.147.8:1621/RZDB

07-yx:
  cdh: cdh6
  username: ggadm
  password: hnsjzx#1_0622
  jdbcUrl: jdbc:oracle:thin:@10.96.119.29:1842/pmshisdb

07-zc:
  cdh: cdh6
  username: ggadm
  password: hnsjzx#1_0622
  jdbcUrl: jdbc:oracle:thin:@10.96.2.215:1821/STANDBY

07-gis:
  cdh: cdh6
  username: ggadm
  password: hnsjzx#1_0644
  jdbcUrl: jdbc:oracle:thin:@10.96.14.156:1821/pwpdg

07-kkx:
  cdh: cdh6
  username: ggadm
  password: hnsjzx#1_0622
  jdbcUrl: jdbc:oracle:thin:@10.96.2.215:1821/STANDBY

07-rz:
  cdh: cdh6
  username: ggadm
  password: hnsjzx#1_0366
  jdbcUrl: jdbc:oracle:thin:@10.96.2.211:1821/standby


01-zc:
  cdh: cdh6
  username: ggadm
  password: ogg#4567
  jdbcUrl: jdbc:oracle:thin:@10.121.180.69:1523/LCAMDBDG1

01-gis:
  cdh: cdh6
  username: ggadm
  password: ogg#4567
  jdbcUrl: jdbc:oracle:thin:@10.121.180.66:1523/GISEHV

01-cw:
  cdh: cdh6
  username: ggadm
  password: ogg#4567
  jdbcUrl: jdbc:oracle:thin:@10.121.181.160:1523/plusdb


01-rz:
  cdh: cdh6
  username: ggadm
  password: ogg#4567
  jdbcUrl: jdbc:oracle:thin:@10.121.192.6:1523/HRSCDB

02-zc:
  cdh: cdh6
  username: c##ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.152.5.153:1522/lcam11g

02-gis:
  cdh: cdh6
  username: ggadm
  password: ogg#4567
  jdbcUrl: jdbc:oracle:thin:@10.121.180.66:1523/GISEHV

02-cw:
  cdh: cdh6
  username: ggadm
  password: goldengate#123
  jdbcUrl: jdbc:oracle:thin:@10.152.4.34:1522/plusdb


02-rz:
  cdh: cdh6
  username: PGC_SJZL
  password: pgc_sjzl#020
  jdbcUrl: jdbc:oracle:thin:@10.152.3.117:1522/RZDB

00-rz:
  cdh: cdh6
  username: ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.92.210.36/rzdb

00-wp:
  cdh: cdh6
  username: ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.92.210.36/rzdb

00-ds:
  cdh: cdh6
  username: ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.92.206.236:1523/nwebsdb

00-zc:
  cdh: cdh6
  username: ggadm
  password: goldengate123
  jdbcUrl: jdbc:oracle:thin:@10.92.210.67:1522/LCAMDB

00-cw:
  cdh: cdh6
  username: ggadm
  password: GgADM_9999
  jdbcUrl: jdbc:oracle:thin:@10.92.213.119:1522/nwzbyjtp


00-cw1:
  cdh: cdh6
  username: ggadm
  password: GgADM_9999
  jdbcUrl: jdbc:oracle:thin:@10.92.213.119:1522/nwzbyjtp

00-cw2:
  cdh: cdh6
  username: ggadm
  password: GgADM_0000
  jdbcUrl: jdbc:oracle:thin:@10.92.213.119:1522/nwzbejtp

15-cw:
  cdh: cdh6
  username: ggadm
  password: GgADM_0800
  jdbcUrl: jdbc:oracle:thin:@10.92.213.114:1522/nwkyzstp

13-cw:
  cdh: cdh6
  username: ggadm
  password: GgADM_1000
  jdbcUrl: jdbc:oracle:thin:@10.92.213.114:1522/nwnyzstp

10-cw:
  cdh: cdh6
  username: ggadm
  password: Ggadm.82
  jdbcUrl: jdbc:oracle:thin:@10.92.220.82:1522/nwcwtp

21-cw:
  cdh: cdh6
  username: ggadm
  password: GgADM_1800
  jdbcUrl: jdbc:oracle:thin:@10.92.220.156:1522/dxzstp

12-cw:
  cdh: cdh6
  username: ggadm
  password: NYggadm_218
  jdbcUrl: jdbc:oracle:thin:@10.92.221.217:1522/nyfztp

16-cw:
  cdh: cdh6
  username: ggadm
  password: GgADM_2000
  jdbcUrl: jdbc:oracle:thin:@10.92.221.207:1522/nwwzzsdb

09-rz:
  cdh: cdh6
  username: NWRZCJ
  password: '''"NWRZCJ123#"'''
  jdbcUrl: jdbc:dm://10.150.46.80:5237
07-cw:
  cdh: cdh6
  username: FMIS0500
  password: Fmis_hn0500
  jdbcUrl: jdbc:dm://10.96.0.95:6235
